"""
Constantes visuais e de negócio do Dashboard RC.
"""

from __future__ import annotations

AMAGGI_GREEN = "#23A067"
AMAGGI_GREEN_2 = "#23A067"
AMAGGI_BLUE = "#00629E"
AMAGGI_YELLOW = "#FACD6A"
LIGHT_GRAY = "#EBEBEC"
DARK_GRAY = "#4A4A4A"
WHITE = "#FFFFFF"
BORDER = "#D1D3D4"
TEXT_MUTED = "#4A4A4A"

# Nova nomenclatura solicitada para o acompanhamento executivo.
STAGE_ORDER = ["SEM LANÇAMENTO", "SEM PEDIDO", "SEM NF", "CONCLUÍDO"]

ETAPA_COLORS = {
    "SEM LANÇAMENTO": "#D32F2F",
    "SEM PEDIDO": "#F2A900",
    "SEM NF": "#00629E",
    "CONCLUÍDO": "#23A067",
}

ETAPA_ROW_COLORS = {
    "SEM LANÇAMENTO": "#FDECEC",
    "SEM PEDIDO": "#FFF7DB",
    "SEM NF": "#E7F1F9",
    "CONCLUÍDO": "#E9F7EF",
}

CANONICAL_COLUMNS = [
    "DATA DE RECEBIMENTO",
    "DATA LANÇAMENTO",
    "PREFIXO",
    "EQUIPAMENTO",
    "FORNECEDOR",
    "Nº ORÇAMENTO FINAL",
    "VALOR SERVIÇO",
    "VALOR PEÇAS",
    "VALOR TOTAL",
    "SOLICITANTE",
    "Nº ORDEM SERVIÇO",
    "Nº REQUISIÇÃO",
    "Nº PEDIDO DE COMPRA",
    "DATA DO PEDIDO",
    "Nº NFS/DANFE",
    "DATA LANÇAMENTO NFS",
    "STATUS",
    "OBS ADICIONAIS",
    "DIAS SEM MOVIMENTO",
    "SLA STATUS",
    "SLA VENCIDO",
    "DONO DA AÇÃO",
    "FAIXA ATRASO",
]

DATE_COLUMNS = [
    "DATA DE RECEBIMENTO",
    "DATA LANÇAMENTO",
    "DATA DO PEDIDO",
    "DATA LANÇAMENTO NFS",
]

VALUE_COLUMNS = ["VALOR SERVIÇO", "VALOR PEÇAS", "VALOR TOTAL"]

FILTER_DEFINITIONS = [
    ("SOLICITANTE", "Solicitante"),
    ("FORNECEDOR", "Fornecedor"),
    ("MES_RECEBIMENTO", "Mês"),
]

TABLE_COLUMNS = [
    "ETAPA",
    "DIAS PARADO",
    "SLA STATUS",
    "DONO DA AÇÃO",
    "FAIXA ATRASO",
    "DATA DE RECEBIMENTO",
    "DATA LANÇAMENTO",
    "PREFIXO",
    "EQUIPAMENTO",
    "FORNECEDOR",
    "Nº ORÇAMENTO FINAL",
    "VALOR SERVIÇO",
    "VALOR PEÇAS",
    "VALOR TOTAL",
    "SOLICITANTE",
    "Nº ORDEM SERVIÇO",
    "Nº REQUISIÇÃO",
    "Nº PEDIDO DE COMPRA",
    "DATA DO PEDIDO",
    "Nº NFS/DANFE",
    "DATA LANÇAMENTO NFS",
    "STATUS",
    "OBS ADICIONAIS",
]
