import { useQuery } from "@tanstack/react-query";
import { BarChart3, Download, LineChart as LineIcon, RefreshCw } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "@/lib/api";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, PageHeader, Select, Skeleton } from "@/components/ui";

const tooltipStyle = { borderRadius: 12, border: "1px solid hsl(var(--border))", background: "hsl(var(--popover))", boxShadow: "0 16px 48px rgba(8,18,28,.16)", fontSize: 12 };

export default function AnalyticsPage() {
  const { data, isLoading, refetch, isFetching } = useQuery({ queryKey: ["analytics"], queryFn: () => api.analytics() });
  return <>
    <PageHeader title="Análises" description="Entenda evolução, prazos, custos e concentração da demanda." actions={<><Select><option>Este ano</option><option>Últimos 6 meses</option><option>Este mês</option></Select><Select><option>Todas as áreas autorizadas</option><option>PCM</option><option>Agrícola</option></Select><Button variant="outline" size="icon" onClick={() => refetch()}><RefreshCw className={`h-4 w-4 ${isFetching ? "animate-spin" : ""}`} /></Button><Button variant="outline"><Download className="h-4 w-4" />Exportar</Button></>} />
    <div className="mb-5 flex gap-1 overflow-x-auto rounded-xl border border-border bg-card p-1 sm:w-fit">{["Resumo", "Prazos e gargalos", "Custos", "Fornecedores", "Solicitantes", "Equipamentos"].map((tab, i) => <button key={tab} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-medium transition ${i === 0 ? "bg-primary-subtle text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{tab}</button>)}</div>
    {isLoading || !data ? <AnalyticsSkeleton /> : <>
      <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
        <Card><CardHeader><div><CardTitle className="flex items-center gap-2"><LineIcon className="h-4 w-4 text-primary" />Recebidas x concluídas</CardTitle><CardDescription>O volume concluído acompanha a entrada de novas solicitações?</CardDescription></div></CardHeader><CardContent className="h-[330px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly} margin={{ top: 16, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="received" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={0.26} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="hsl(var(--border))" vertical={false} strokeDasharray="3 6" /><XAxis dataKey="month" tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => formatNumber(Number(value))} /><Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 12 }} /><Area type="monotone" dataKey="received" name="Recebidas" stroke="hsl(var(--primary))" strokeWidth={2.3} fill="url(#received)" /><Line type="monotone" dataKey="completed" name="Concluídas" stroke="hsl(var(--success))" strokeWidth={2.3} dot={false} /></AreaChart></ResponsiveContainer></CardContent></Card>
        <Card><CardHeader><div><CardTitle>Onde estão as solicitações</CardTitle><CardDescription>Quantidade por etapa documental.</CardDescription></div></CardHeader><CardContent className="h-[330px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.flow} layout="vertical" margin={{ top: 12, right: 20, left: 20, bottom: 0 }}><CartesianGrid stroke="hsl(var(--border))" horizontal={false} strokeDasharray="3 6" /><XAxis type="number" hide /><YAxis type="category" dataKey="label" width={100} tickLine={false} axisLine={false} fontSize={11} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => formatNumber(Number(value))} /><Bar dataKey="count" name="Solicitações" fill="hsl(var(--primary))" radius={[0, 7, 7, 0]} barSize={22} /></BarChart></ResponsiveContainer></CardContent></Card>
      </section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2">
        <Card><CardHeader><div><CardTitle>Tempo em aberto</CardTitle><CardDescription>Distribuição das solicitações em andamento por faixa.</CardDescription></div></CardHeader><CardContent className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.aging} margin={{ top: 12, right: 8, left: -10, bottom: 0 }}><CartesianGrid stroke="hsl(var(--border))" vertical={false} strokeDasharray="3 6" /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="count" name="Solicitações" fill="hsl(var(--primary))" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card>
        <Card><CardHeader><div><CardTitle>Serviços x peças</CardTitle><CardDescription>Composição mensal dos valores das solicitações.</CardDescription></div></CardHeader><CardContent className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.costs} margin={{ top: 12, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="hsl(var(--border))" vertical={false} strokeDasharray="3 6" /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} tickFormatter={(v) => formatCurrency(Number(v), true)} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => formatCurrency(Number(value))} /><Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 12 }} /><Bar dataKey="serviceCents" name="Serviços" stackId="a" fill="hsl(var(--primary))" radius={[0,0,0,0]} /><Bar dataKey="partsCents" name="Peças" stackId="a" fill="hsl(var(--success))" radius={[7,7,0,0]} /></BarChart></ResponsiveContainer></CardContent></Card>
      </section>
      <section className="mt-5 grid gap-5 lg:grid-cols-3">{[["Fornecedores", data.suppliers], ["Solicitantes", data.requesters], ["Equipamentos", data.equipment]].map(([title, items]) => <Card key={String(title)}><CardHeader><div><CardTitle>{String(title)} em destaque</CardTitle><CardDescription>Maior volume de solicitações no período.</CardDescription></div><BarChart3 className="h-4 w-4 text-primary" /></CardHeader><CardContent className="space-y-3">{(items as typeof data.suppliers).slice(0,5).map((item, index) => <div key={item.name} className="flex items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted text-xs font-semibold text-muted-foreground">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{item.secondary ?? (item.amountCents ? formatCurrency(item.amountCents, true) : "")}</p></div><span className="numeric text-sm font-semibold">{item.count}</span></div>)}</CardContent></Card>)}</section>
    </>}
  </>;
}
function AnalyticsSkeleton() { return <div className="grid gap-5 xl:grid-cols-2"><Skeleton className="h-[420px] rounded-2xl" /><Skeleton className="h-[420px] rounded-2xl" /><Skeleton className="h-[340px] rounded-2xl" /><Skeleton className="h-[340px] rounded-2xl" /></div>; }
